# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e012ec7fb324535ac5af05aed35cb2c185491afe661b59429d4997556a83fabe426ed0a2d8ecf3d07018b6f9f598379b6e1c0ce0348a95105944d476393179c

test:
  secret_key_base: d4e55ca494d8ffddd1700b58cc68af5c12b33842e7ee3f17de9418659e3be349bc2f42f87a773b25fa70cecd7e6685f756dce280cb8da8661059d71f947df04d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
